// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2jGc2EK7b-5Nvu05DNfAxsASObYaDnUA',
    appId: '1:749600611860:web:bf3817250710a410c21101',
    messagingSenderId: '749600611860',
    projectId: 'e-commrec-app',
    authDomain: 'e-commrec-app.firebaseapp.com',
    storageBucket: 'e-commrec-app.appspot.com',
    measurementId: 'G-NLQFW2G85N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5pURtsTJRJ8MDxtIPpy4M1ZmD-8LT-nU',
    appId: '1:749600611860:android:353cf283dc86d146c21101',
    messagingSenderId: '749600611860',
    projectId: 'e-commrec-app',
    storageBucket: 'e-commrec-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF-W1OIeS4Pq-WpTETzRIJhUY1w2MOztk',
    appId: '1:749600611860:ios:9dbacdbd62d6db80c21101',
    messagingSenderId: '749600611860',
    projectId: 'e-commrec-app',
    storageBucket: 'e-commrec-app.appspot.com',
    iosClientId: '749600611860-lgu5artv6mtphhcep4fkh36v2kg0q7md.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF-W1OIeS4Pq-WpTETzRIJhUY1w2MOztk',
    appId: '1:749600611860:ios:9dbacdbd62d6db80c21101',
    messagingSenderId: '749600611860',
    projectId: 'e-commrec-app',
    storageBucket: 'e-commrec-app.appspot.com',
    iosClientId: '749600611860-lgu5artv6mtphhcep4fkh36v2kg0q7md.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceAdmin',
  );
}
